#ifndef GLOBAL_H
#define GLOBAL_H

#include <Arduboy2.h>
#include <ArduboyTones.h>
#include "images.h"

#define FPS 60
#define INTERVAL_LENGTH 30
#define TITLE_OPTION_COUNT 3
#define TITLE_IMAGE_X 5
#define TITLE_IMAGE_Y 6
#define TITLE_PLAY_TEXT_X 56
#define TITLE_PLAY_TEXT_Y 38
#define TITLE_INFO_TEXT_X 56
#define TITLE_INFO_TEXT_Y 45
#define TITLE_SFX_ON_TEXT_X 52
#define TITLE_SFX_ON_TEXT_Y 52
#define TITLE_SFX_OFF_TEXT_X 50
#define TITLE_SFX_OFF_TEXT_Y TITLE_SFX_ON_TEXT_Y
#define TITLE_CURSOR_SIZE 2
#define TITLE_CURSOR_X_OFFSET 3
#define TITLE_CURSOR_Y_OFFSET 1
#define LAST_TITLE_OPTION TITLE_OPTION_COUNT - 1

#define INFO_IMAGE_X 11
#define INFO_IMAGE_Y 4

#define QUEST_GRAVE_INDEX 5
#define QUEST_CURSOR_OFFSET_X 8
#define QUEST_CURSOR_OFFSET_Y 4
#define QUEST_CURSOR_ANIMATION_INTERVAL 10
#define QUEST_CURSOR_ANIMATION_MAX_OFFSET 1
#define QUEST_CURSOR_ANIMATION_MIN_OFFSET -1

#define ENEMY_COUNT 5
#define LAST_ENEMY ENEMY_COUNT - 1

#define ENEMY_PANEL_X 104
#define ENEMY_PANEL_Y 0
#define ENEMY_PANEL_WIDTH 24
#define ENEMY_PANEL_HEIGHT 64

#define ENEMY_PORTRAIT_X 106
#define ENEMY_PORTRAIT_Y 2

#define ENEMY_HEALTH_X 106
#define ENEMY_HEALTH_Y 60
#define ENEMY_HEALTH_WIDTH 20
#define ENEMY_HEALTH_HEIGHT 2

#define HEARTS_MAX 3
#define HEART_SPACING 1

#define NUMBER_SPACING 2

#define SCORE_INCREMENT 10

#define WEAPON_COUNT 4

#define ENEMY_DATA_LENGTH 5
#define ENEMY_DATA_TYPE 0
#define ENEMY_DATA_HEALTH 1
#define ENEMY_DATA_MODIFIER 2

#define BATTLE_PAUSED_TEXT_X 50
#define BATTLE_PAUSED_TEXT_Y 28
#define BATTLE_HEARTS_X 2
#define BATTLE_HEARTS_Y 2
#define BATTLE_SCORE_X 97
#define BATTLE_SCORE_Y 2
#define BATTLE_CURSOR_MAX 2

#define WEAPON_ACTIVE_X 0
#define WEAPON_ACTIVE_Y 14
#define WEAPON_ACTIVE_WIDTH 12
#define WEAPON_ACTIVE_HEIGHT 12
#define WEAPON_ICON_X 2
#define WEAPON_ICON_Y 16
#define WEAPON_SPACING 4
#define WEAPON_DIVIDER_WIDTH 1
#define WEAPON_DIVIDER_HEIGHT 10
#define WEAPON_DIVIDER_LEFT_X 14
#define WEAPON_DIVIDER_RIGHT_X 89
#define WEAPON_DIVIDER_Y 15

class Game;

enum GAME_STATES {
  GAME_STATE_TITLE,
  GAME_STATE_INFO,
  GAME_STATE_QUEST,
  GAME_STATE_BATTLE,
  GAME_STATE_GAME_OVER,
  GAME_STATE_WIN
};

enum TITLE_STATES {
  TITLE_STATE_PLAY,
  TITLE_STATE_INFO,
  TITLE_STATE_SFX
};

enum ENEMY_TYPES {
  ENEMY_TYPE_SKELETON,
  ENEMY_TYPE_ORC,
  ENEMY_TYPE_GOLEM,
  ENEMY_TYPE_DEMON,
  ENEMY_TYPE_SORCERER
};

enum WEAPON_TYPES {
  WEAPON_TYPE_SWORD,
  WEAPON_TYPE_HAMMER,
  WEAPON_TYPE_ARROW,
  WEAPON_TYPE_STAFF
};

extern Arduboy2 arduboy;
extern Sprites sprites;
extern ArduboyTones sound;

#endif
